//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jarat
    {
        public int jaratszam { get; set; }
        public string honnan { get; set; }
        public string hova { get; set; }
        public System.DateTime indulasido { get; set; }
        public System.DateTime visszaindulasido { get; set; }
        public bool terminal { get; set; }
        public int rgepkod { get; set; }
        public int jegyar { get; set; }
    }
}
