//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kedvezmenyek
    {
        public int kedvAz { get; set; }
        public string kedvNeve { get; set; }
        public int kedvMerteke { get; set; }
    }
}
