//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class repuloter_projectEntities : DbContext
    {
        public repuloter_projectEntities()
            : base("name=repuloter_projectEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alkalmazottifiokok> alkalmazottifiokok { get; set; }
        public virtual DbSet<jarat> jarat { get; set; }
        public virtual DbSet<kedvezmenyek> kedvezmenyek { get; set; }
        public virtual DbSet<meret> meret { get; set; }
        public virtual DbSet<repgeptars> repgeptars { get; set; }
        public virtual DbSet<repulogep> repulogep { get; set; }
        public virtual DbSet<utas> utas { get; set; }
        public virtual DbSet<utazas> utazas { get; set; }
    }
}
