//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class repulogep
    {
        public int rgepkod { get; set; }
        public string tipus { get; set; }
        public int meretAz { get; set; }
        public int rgepTarsAz { get; set; }
    }
}
