//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utas
    {
        public int utasAz { get; set; }
        public string nev { get; set; }
        public System.DateTime szulido { get; set; }
        public int szemAzon { get; set; }
        public int kedvAz { get; set; }
        public string felhasznalonev { get; set; }
        public string jelszo { get; set; }
        public string email { get; set; }
        public double mobiltelefonszam { get; set; }
    }
}
