//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace repuloterProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class utazas
    {
        public int utazasAz { get; set; }
        public int jaratszamAz { get; set; }
        public int utasAz { get; set; }
        public int osztaly { get; set; }
    }
}
